name: Docker Image CI

env:
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  REPO_NAME: ${{secrets.REPO_NAME}}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: 'Create env file'
      run:
          touch .env
          echo MONGODB_URL="${{secrets.MONGODB_URL}}" >> .env
          echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
    - name: docker login
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Build docker Image
      run: docker build -t reddint-backend:latest .
    
    - name: Docker push
      run: docker push $DOCKER_USER/$REPO_NAME:latest
  
